FROM openjdk:11
ADD target/StockExchangeApplicationApi-0.0.1-SNAPSHOT.jar StockExchangeApplicationApi-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "StockExchangeApplicationApi-0.0.1-SNAPSHOT.jar"]


